[build]
  install = "npm install --include=dev"
  command = "node ./node_modules/vite/bin/vite.js build --config vite.config.ts"
  publish = "dist"

[context.production.environment]
  NPM_FLAGS = "--include=dev"
